<script lang="ts">
	import { onMount } from 'svelte';
	import { bufferToWave } from '../utils/audio';

	let AudioContext;
	let audioCtx: AudioContext;
	let oscillator: OscillatorNode;
	let gainNode: GainNode;
	onMount(() => {
		AudioContext = window.AudioContext || window.webkitAudioContext;
		audioCtx = new AudioContext();
	});

	// onDestroy(() => {
	//     oscillator.stop();
	// });

	let files: FileList | null = null;

	$: if (files) {
		for (const file of files) {
			console.log(`${file.name}: ${file.size} bytes`);
		}
	}

	let imagePath: string | null = './example.png';
	let frequency = 100;
	const onFileSelected = (e: Event) => {
		const target = e.target as HTMLInputElement;
		let image = target.files ? target.files[0] : null;
		if (!image) return;

		let reader = new FileReader();
		reader.readAsDataURL(image);
		reader.onload = (e) => {
			const target = e.target as FileReader;
			imagePath = target.result as string;
			const img = new Image();
			img.src = imagePath;
			img.onload = () => {
				const { r, g, b } = getAverageRGB(img);
				frequency = (r + g + b) / 3;
			};
		};
	};

	const getAverageRGB = (imgEl: HTMLImageElement) => {
		const blockSize = 5; // only visit every 5 pixels
		const defaultRGB = { r: 0, g: 0, b: 0 }; // for non-supporting envs
		let canvas = document.createElement('canvas');
		let context = canvas.getContext && canvas.getContext('2d');
		let data;
		let width;
		let height;
		let i = -4;
		let length;
		let rgb = { r: 0, g: 0, b: 0 };
		let count = 0;

		if (!context) {
			return defaultRGB;
		}

		height = canvas.height = imgEl.naturalHeight || imgEl.offsetHeight || imgEl.height;
		width = canvas.width = imgEl.naturalWidth || imgEl.offsetWidth || imgEl.width;

		context.drawImage(imgEl, 0, 0);
		try {
			data = context.getImageData(0, 0, width, height);
		} catch (e) {
			/* security error, img on diff domain */
			return defaultRGB;
		}

		length = data.data.length;

		while ((i += blockSize * 4) < length) {
			++count;
			rgb.r += data.data[i];
			rgb.g += data.data[i + 1];
			rgb.b += data.data[i + 2];
		}

		// ~~ used to floor values
		rgb.r = ~~(rgb.r / count);
		rgb.g = ~~(rgb.g / count);
		rgb.b = ~~(rgb.b / count);

		return rgb;
	};

	let isPlaying = false;

	const handlePlay = () => {
		// create Oscillator and gain node
		oscillator = audioCtx.createOscillator();
		gainNode = audioCtx.createGain();

		// connect oscillator to gain node to speakers
		oscillator.connect(gainNode);
		gainNode.connect(audioCtx.destination);

		oscillator.frequency.value = frequency;
		oscillator.start(0);
		oscillator.connect(audioCtx.destination);
		isPlaying = true;
	};

	const handleStop = () => {
		oscillator.disconnect(audioCtx.destination);
		oscillator.stop();
		isPlaying = false;
	};

	let duration = 5;
	const handleDownload = () => {
		// download the audio generated by the oscillator in duration seconds
		const sampleRate = audioCtx.sampleRate;
		const numberOfChannels = 1; // 单声道
		const bufferSize = sampleRate * duration;
		const audioBuffer = audioCtx.createBuffer(numberOfChannels, bufferSize, sampleRate);
		const channelData = audioBuffer.getChannelData(0);
		for (let i = 0; i < bufferSize; i++) {
			channelData[i] = Math.sin((i / sampleRate) * 2 * Math.PI * frequency);
		}
		var new_file = URL.createObjectURL(bufferToWave(audioBuffer, bufferSize));

		var download_link = document.createElement('a');
		download_link.href = new_file;
		download_link.download = 'result.wav';
		download_link.click();
	};
</script>

<h1>Image2Audio Art</h1>
<h2>Upload a picture:</h2>
<input
	accept="image/png, image/jpeg"
	bind:files
	id="image"
	name="avatar"
	type="file"
	on:change={(e) => onFileSelected(e)}
/>
<h2>Preview:</h2>
<img src={imagePath} alt="please upload" style="max-height: 400px" />
<h2>Result:</h2>
<div>frequency: {frequency}</div>
<button disabled={isPlaying} on:click={handlePlay}>Play</button>
<button disabled={!isPlaying} on:click={handleStop}>Stop</button>
<div>
	<h2>Download:</h2>
	<div>duration: {duration}</div>
	<input type="range" bind:value={duration} min="1" max="20" />
	<br />
	<button on:click={handleDownload}>Download</button>
</div>

{#if files}
	<h2>Selected files:</h2>
	{#each Array.from(files) as file}
		<p>{file.name} ({file.size} bytes)</p>
	{/each}
{/if}
